import React, { useState } from 'react'
import Modal from '@/components/ui/Modal'
import { markMatchAsSent } from '@/firebase/firestore'
import { useToastStore } from '@/components/ui/Toast'
import useMatchStore from '@/store/matchStore'
import useClientStore from '@/store/clientStore'

export default function SendMatchModal({ isOpen, onClose, client, matchResult }) {
  const { profile, score, tier, introText } = matchResult
  
  // Local state for the editable intro text
  const [editedText, setEditedText] = useState(introText)
  const [isSending, setIsSending] = useState(false)
  
  const addToast = useToastStore((s) => s.addToast)
  const markSentLocally = useMatchStore((s) => s.markSentLocally)
  const updateClientLocally = useClientStore((s) => s.updateClientLocally)

  const handleSend = async () => {
    setIsSending(true)
    try {
      // 1. Perform background Firestore update
      await markMatchAsSent(client.id, profile.id)
      
      // 2. Optimistic UI updates
      markSentLocally(profile.id)
      const currentSent = client.sentMatches || []
      updateClientLocally(client.id, { sentMatches: [...currentSent, profile.id] })
      
      // 3. Notify success
      addToast({
        type: 'success',
        title: 'Match Sent!',
        message: `Profile sent to ${client.personal.firstName}.`,
      })
      onClose()
    } catch (err) {
      addToast({
        type: 'error',
        title: 'Failed to send match',
        message: 'Please try again.',
      })
    } finally {
      setIsSending(false)
    }
  }

  return (
    <Modal isOpen={isOpen} onClose={onClose} title={`Send Match to ${client.personal.firstName}`}>
      <div className="space-y-6">
        
        {/* Match Summary Header */}
        <div className="bg-surface-50 p-4 rounded-xl border border-surface-200 flex items-center justify-between">
          <div>
            <h3 className="text-sm font-bold text-surface-900">
              Sending: {profile.personal.firstName} {profile.personal.lastName}
            </h3>
            <p className="text-sm text-surface-600 mt-1">
              {profile.personal.city} • {profile.professional?.designation}
            </p>
          </div>
          <div className="text-right">
            <div className="text-2xl font-black text-brand">{score}%</div>
            <div className="text-xs font-semibold text-surface-500 uppercase">{tier}</div>
          </div>
        </div>

        {/* Intro Text Editor */}
        <div>
          <label className="block text-sm font-semibold text-surface-900 mb-2">
            Matchmaker Introduction
          </label>
          <p className="text-xs text-surface-500 mb-3 leading-relaxed">
            This intro was generated by the engine based on their specific compatibility profile. 
            Review and edit it before sending to the client.
          </p>
          <textarea
            value={editedText}
            onChange={(e) => setEditedText(e.target.value)}
            className="input-field w-full h-32 resize-none"
            placeholder="Write an introduction..."
          />
        </div>

        {/* Action Buttons */}
        <div className="flex items-center justify-end gap-3 pt-4 border-t border-surface-200">
          <button
            onClick={onClose}
            className="btn-secondary"
            disabled={isSending}
          >
            Cancel
          </button>
          <button
            onClick={handleSend}
            className="btn-primary flex items-center gap-2"
            disabled={isSending || !editedText.trim()}
          >
            {isSending ? (
              <>
                <svg className="animate-spin -ml-1 mr-2 h-4 w-4 text-white" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                </svg>
                Sending...
              </>
            ) : (
              'Send to Client'
            )}
          </button>
        </div>
      </div>
    </Modal>
  )
}
